### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'paintings'!

### ISSUE THREAD

**Issue by TewMon** [ArtixAllMighty/Paintings--#100]
fabric version for 1.20.4 and that error comes up
[crash-2024-04-10_12.11.16-client.txt](https://github.com/AbsolemJackdaw/Paintings--/files/14931359/crash-2024-04-10_12.11.16-client.txt)

**Comment by NigelsNutInLaw** [comment]
I'm also crashing
[crash-2024-04-28_18.32.16-client.txt](https://github.com/AbsolemJackdaw/Paintings--/files/15141072/crash-2024-04-28_18.32.16-client.txt)

**Comment by AbsolemJackdaw** [comment]
> fabric version for 1.20.4 and that error comes up [crash-2024-04-10_12.11.16-client.txt](https://github.com/AbsolemJackdaw/Paintings--/files/14931359/crash-2024-04-10_12.11.16-client.txt)

You are missing the common networking library

**Comment by AbsolemJackdaw** [comment]
> I'm also crashing [crash-2024-04-28_18.32.16-client.txt](https://github.com/AbsolemJackdaw/Paintings--/files/15141072/crash-2024-04-28_18.32.16-client.txt)

Your crash is different. The mod can't read the list of resourcepacks for some reason. the input stream reader fails. 

The first issue in this ticket has been solved, so i'm closing the issue. 
Please make a new ticket with your issue and provide as much detail as possible. 
Have you got all dependencies installed?

**Comment by Poopooracoocoo** [comment]
> > fabric version for 1.20.4 and that error comes up [crash-2024-04-10_12.11.16-client.txt](https://github.com/AbsolemJackdaw/Paintings--/files/14931359/crash-2024-04-10_12.11.16-client.txt)
> 
> You are missing the common networking library

That dependency should be declared in your fabric.mod.json so it doesn't crash :)
