### ISSUE TITLE
Images not loading for paintings

### ISSUE THREAD

**Issue by MfknSorcerer** [ArtixAllMighty/Paintings--#101]
I followed the instructions and made a resource pack with optimized images and put it in the folder. The paintings are showing up, but the images are not, only pink and black checkers.

1.19.2

**Comment by AbsolemJackdaw** [comment]
Have you made sure that the resourcepack is selected in the vanilla resourcepack GUI?

**Comment by MfknSorcerer** [comment]
That was it, thank you!
