### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by NigelsNutInLaw** [ArtixAllMighty/Paintings--#102]
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'paintings'!"
Exit code: -1

[crash-2024-04-29_19.22.54-client.txt](https://github.com/AbsolemJackdaw/Paintings--/files/15146150/crash-2024-04-29_19.22.54-client.txt)

In the other ticket you said 
"You are missing the common networking library" 
[Do you mean this Mod?](https://www.curseforge.com/minecraft/mc-mods/common-network) 
With this the game launched but when i try to place a painting I am disconnected from the server?(playing single player) and I'm returned to the server list. when I remove Paintings++ from my mod folder the game launches and I game seems to work fine

Dependencies (according to curseforge)
![Screenshot 2024-04-29 194616](https://github.com/AbsolemJackdaw/Paintings--/assets/47041315/c1a55bd4-8c2d-4307-97fb-ae2a3364e717)

Screenshot of other mods I have installed
![Screenshot 2024-04-29 202507](https://github.com/AbsolemJackdaw/Paintings--/assets/47041315/bdb62a22-7de9-407f-9cb5-234b6c647af0)

Crash screen
![Screenshot 2024-04-29 194906](https://github.com/AbsolemJackdaw/Paintings--/assets/47041315/fd928c62-01be-41c2-b4ba-57125d576732)

If you need any more info I'll do my best

**Comment by AbsolemJackdaw** [comment]
it seems i forgot tot tage common network as a dependency.

**Comment by AbsolemJackdaw** [comment]
fixed in 12.0.0.3
