### ISSUE TITLE
Clutter on the GUI

### ISSUE THREAD

**Issue by Plast15** [ArtixAllMighty/Paintings--#104]
In older editions of the mod i would simply just delete the paintings in the jar file and it would work fine but as of 1.20.1 the mod just ends up not letting me place any paintings even if i just remove 1 painting from the json and texture file would it be possible to make a mod version without the paintings added please.

**Comment by AbsolemJackdaw** [comment]
https://legacy.curseforge.com/minecraft/texture-packs/painting-base-painting-pack

**Comment by Plast15** [comment]
Dead URL?

**Comment by AbsolemJackdaw** [comment]
Brand new url, the project still has to be approved :P

**Comment by AbsolemJackdaw** [comment]
the page is the resourcepack. 
1.20.4, version 12.0.0.4 and up has no mroe paintings in the base mod file
