### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'yungsapi'!

### ISSUE THREAD

**Issue by victorino12311** [ArtixAllMighty/Paintings--#106]
[crash-2024-07-07_13.34.54-client.txt](https://github.com/user-attachments/files/16119375/crash-2024-07-07_13.34.54-client.txt)

I've got all the dependencies so I'm not sure what the issue is

**Comment by AbsolemJackdaw** [comment]
Yungsbridges seems to have an issue loading. 
I'd suggest reporting it to the Yung's bridges mod creator. 
There's not a lot I can do at this point I believe.
