### ISSUE TITLE
1.12.2-5.0.0.1 crashes dedicated server Forge 1.12.2 build 2751

### ISSUE THREAD

**Issue by kreezxil** [ArtixAllMighty/Paintings--#13]
Notes:
     on startup

crash report:
https://gist.github.com/28a5b772cbe4124ec8b0f9e39d612f59

fml server latest:
https://gist.github.com/6da79214ddc6d6008ce87119337f0744

**Comment by ArtixAllMighty** [comment]
solved in release 5.0.0.2
