### ISSUE TITLE
Painting Edge Rendering issue - Forge 1.12.2 Build 2611

### ISSUE THREAD

**Issue by Ixtlaxt** [ArtixAllMighty/Paintings--#14]
Hi there, noticed a rendering issue on the painting edges, seems to be affecting top, bottom, and right sides.  Left is unaffected.  Looks to be a second plane being rendered in the same position.
See  screenshots:

![2018-08-23_11 44 19](https://user-images.githubusercontent.com/37380464/44518180-e4ad4c80-a6c9-11e8-8653-a7dfef040d7f.png)
![2018-08-23_11 36 28](https://user-images.githubusercontent.com/37380464/44517989-65b81400-a6c9-11e8-906f-a1a5e444115d.png)
![2018-08-23_11 36 51](https://user-images.githubusercontent.com/37380464/44517997-681a6e00-a6c9-11e8-9da7-937de2d0c08a.png)

**Comment by ArtixAllMighty** [comment]
without further information, I have not been able to solve this. 
lack of response on first question makes me think the user has had it resolved with the solution I proposed earlier
