### ISSUE TITLE
Can't create new painting either in jar or resource pack

### ISSUE THREAD

**Issue by tacogerbil** [ArtixAllMighty/Paintings--#15]
First of all thank you for the mod.. Been using it for years and a day by replacing the original pics with my own (without modifying any of the jsons).
This time I'm trying to create my own image with my own dimensions... It's not working.. 
I've tried various methods.. the configuration I've created is the following --> https://paste.dimdev.org/iyezepikuj.json
The image I've used is the following -->  https://i.imgur.com/BHuoyhp.jpg
Modifying massive.json and massive.png  I got this --> https://i.imgur.com/QflJADW.png
creating a new **json** and **image** named **loony** (within the jar) and modifying the cfg file with my choice... still got --> https://i.imgur.com/QflJADW.png
I created a resource pack and named the new image **massive.png** as well as modified the massive.json file.  It looks like it takes the image but the json it is using is the original in the jar so the images are being chopped up into the same configured ones as the **original** massive.json/png.

Am I doing something wrong??

**Comment by MurphysChaos** [comment]
`PatternLoader` can't find the pattern JSON if it's not inside the JAR file. Intended behavior is it will also check `resourcepacks/<pack>.zip/assets/subaraki/patterns` (or `resources/pack/assets/subaraki/patterns` if loose files are preferred to a zip file).

**Comment by tacogerbil** [comment]
FYI I also modified the jar file with my json and image files.  Same result.
