### ISSUE TITLE
Crash with 5.0.1.0

### ISSUE THREAD

**Issue by ireece1** [ArtixAllMighty/Paintings--#17]
Can't start the game, crashes on boot.

https://pastebin.com/0LMnhf9f

**Comment by MurphysChaos** [comment]
That error is typical of a mod that hasn't been re-obfuscated. Did you happen to build the JAR yourself?

**Comment by xkforce** [comment]
Users aren't going to bother doing that.  https://paste.ee/p/CeJf5  That's the paste with no other mods installed and using the file from curse.  No jar building no nothing.

**Comment by MurphysChaos** [comment]
I'm sorry, but some users would do that, which is why I asked. It wasn't an accusation. Still, I'll continue investigating to see if I can come up with anything.

**Comment by xkforce** [comment]
Fair enough.  What changed in this update?  There's no change log for it.

**Comment by MurphysChaos** [comment]
The update was to address a bug preventing custom patterns from loading.
I've actually managed to fix the crash but now the painting picker won't
show up and it just puts up the first painting in the config.

I've gone ahead and marked version 5.0.1.0 as archived, meaning it won't
list on Twitch. I'll make sure to include changelogs in my next upload.

**Comment by MurphysChaos** [comment]
v5.0.1.1 is now up, complete with an actual changelog. 😊 Please let me know if you have any other issues.
