### ISSUE TITLE
Multiplayer Pattern Verification

### ISSUE THREAD

**Issue by MurphysChaos** [ArtixAllMighty/Paintings--#18]
Add a verification component on the server that tells the client what art collection (painting mode) is being used and, if the collection identifier is different, close the connection with a message to the user.

**Comment by ArtixAllMighty** [comment]
should it close a connection however ? or rather force the config to be overwritten ? 
In essence, the idea is that server configs precede client configs and therefor the client should already have the same setting as the server.  
if anyhow a custom file has been used by the server, then indeed it should show a message.

**Comment by ArtixAllMighty** [comment]
closed by eca32e2
