### ISSUE TITLE
EntityNewPainting extends EntityHanging

### ISSUE THREAD

**Issue by Treehee** [ArtixAllMighty/Paintings--#20]
Some background info:
> I was playing around in my Test mod the other day to get a better understanding of forge Entities, and also made a mod that replaces vanilla paintings. I then decided to look around if such a mod already existed and came across your mod. I was kind of interested to compare our methods, and they are suprisingly similar ^^. There's two main differences (other than your mod being waaaay more polished and having config stuff and all that) that caught my attention. First is that you listen for an onrightclickblock event, then check the players item and essentially copy the vanilla itemhanging placing code, whereas I went with lsitening for entitysummon events, cancelling it if it's class was equal to the entitypainting class and then summoning my own. This doesn't make any difference in practice, but the other thing does:

Your painting replacement entity extends entityhanging instead of entitypainting, which means that any other mod that may check `instanceof EntityPainting` (like maybe a mob that attacks paintings or smth) would be partially incompatible with your mod. This should be easily fixeable by making a couple of midifications to the EntityNewPainting class:

1. make it `extend EntityPainting`
2. add `super.art = EntityPainting.EnumArt.KEBAB;` to the constructor to prevent nullpointer errors in writeEntityToNBT
3. in writeEntityToNBT, swap the two lines of code to make sure your mod overwrites the "Motive" tag, rather than vanilla overwriting yours

**Comment by MurphysChaos** [comment]
Thanks for the tip! I'll look into it.

**Comment by Treehee** [comment]
No problem!

**Comment by ArtixAllMighty** [comment]
our painting doesnt follow any painting logic anymore however, and altough it looks like paintings, is in essence not a painting anymore.
