### ISSUE TITLE
Enigmatica2 Expert - mod not working

### ISSUE THREAD

**Issue by Seth0067** [ArtixAllMighty/Paintings--#21]
I have tried this mod with Enigmatica2 Expert, and the mod does not seem to be working.  Neither the loaded resource file loads, or the GUI appears.

I have tried two different resource files (sphax and new_insane) and have used the exact same resource pack and cfg successfully in a different profile (with fewer mods). Maybe there is a mod conflict with something in this pack?  My list of mods can be seen at:

https://www.modlister.com/user/Seth0067

Any suggestions would be appreciated!

**Comment by ArtixAllMighty** [comment]
is there any other mod that fiddles with the painting item ?

**Comment by ArtixAllMighty** [comment]
marking this issue as stale. 
without further answer or logs I can not help
