### ISSUE TITLE
Add independent texture for missing images

### ISSUE THREAD

**Issue by MurphysChaos** [ArtixAllMighty/Paintings--#25]
When the client pattern doesn't contain the texture indicated by the server, display a placeholder image. Get that placeholder image from a texture independent from the pattern texture.

Minimum requirement: always use a 1x1 placeholder
Stretch goal: parse incoming texture name, for missing textures, and display placeholder matching in-game painting dimensions.

**Comment by ArtixAllMighty** [comment]
laceholder image created, and the painting entity retains its own name without it reverting to default.
keeping the name implies keeping dimensions, and the entity can keep therefor its size and name, and display the missing texture at the correct size.
this also implies an extra addition ot the list of all available paintings for each missing size. 
no idea what kind of problem this might give on large servers.

Issue / idea adressed in 2af79e9
