### ISSUE TITLE
Bad Rendering on Painting Frames [1.12.2]

### ISSUE THREAD

**Issue by DeDevilTAils** [ArtixAllMighty/Paintings--#26]
If I place any painting, including vanilla ones or custom ones, the textures on the sides of the picture frame look like a glitchy mess. If I move around while I'm looking at them it's as if they're flickering between two different textures at once. The problem seems to be worse on larger paintings; for 1x1 paintings sometimes only the right and bottom edges of the frame suffer from the glitch. I'm having this problem with just Paintings++ installed, I have no other mods.

![20190901161802_1](https://user-images.githubusercontent.com/55362629/64926944-d3dde600-d7b8-11e9-8fc5-f56a4d1b44fe.jpg)
![20190901161829_1](https://user-images.githubusercontent.com/55362629/64926963-1bfd0880-d7b9-11e9-9c5d-b69e2f49bdc4.jpg)
![20190901162410_1](https://user-images.githubusercontent.com/55362629/64926967-20c1bc80-d7b9-11e9-9a72-aedc9233698f.jpg)

**Comment by ArtixAllMighty** [comment]
I tried up untill the current 1.14.4 update to pinpoint the issue. I couldn't find it sadly enough. 
I did try some new things. Itm ight be solved, it might not. 
You'll have to stick with this graphical issue till you update to 1.14.4 I'm afraid
