### ISSUE TITLE
Dont load Texturepack

### ISSUE THREAD

**Issue by ms96sc** [ArtixAllMighty/Paintings--#27]
Hello,

i have made a Texturepack write the Gide from the Website.

But the mod loads the Minecraft vanila Paintings,in the Config i have change to gibea layout.

Can somebody help me?

(Google Translator)

**Comment by ms96sc** [comment]
*it ist loading some Picture vom Vanilla and from the Texturepack. And i will that it loads only from the Texturepack.

**Comment by ArtixAllMighty** [comment]
what version are you using ? 
are there any vanilla paintings in your template ?

**Comment by ms96sc** [comment]
I realize that was not the only problem he still takes pictures from the default textures.

I use the lastest version from the mod and i play Direwolf 20

**Comment by ArtixAllMighty** [comment]
In Gibea, the base layout _has vanilla paintings in it_

unless you can provide me with a picture of your template, i can't help. this just sounds like logic.

if you made your own template, make sure to enter your template's name, and also make sure it fits both the layout json and png names

**Comment by ArtixAllMighty** [comment]
it might also be that the path in your resourcepack is completely wrong, but i cant tell, i have no info to work with

**Comment by ms96sc** [comment]
Hi,
I found the problem I made a new texture pack and always forgot the pack.mcmeta file. True, my mistake.

**Comment by ArtixAllMighty** [comment]
aha ! thought something like that :) glad we got it solved !
