### ISSUE TITLE
Suggestion: higher res pictures (when texturepacks like Faithful are active)

### ISSUE THREAD

**Issue by SepSol** [ArtixAllMighty/Paintings--#28]
[Faithful](https://faithful.team/) has the exact textures of vanilla Minecraft but with higher res, it would make sense for them to have higher res paintings:

![2019-10-19_22 13 37](https://user-images.githubusercontent.com/47871887/67149923-2e89c680-f2be-11e9-8c70-a4d107f755f6.png)

![2019-10-19_22 16 06](https://user-images.githubusercontent.com/47871887/67149924-321d4d80-f2be-11e9-97f3-045b93365291.png)

**Comment by ArtixAllMighty** [comment]
are they not ? 
if you want high res paintings, make high res paintings. 
The base paintings my mod provides are x16 resolution.
This is the work of either the Resourcepack or the End user

**Comment by SepSol** [comment]
I put a vanilla painting and Paintings++ painting side by side abd toggled Faithful for demonstration. Faithful team has done the vanilla paintings. I thought you have the source higher res files for your paintings and could somehow make a Faithful addon.

**Comment by ArtixAllMighty** [comment]
no, i painted them like that.
I won't be making an addon though.
You could always ask Faithfull to add mod support =)

**Comment by SepSol** [comment]
ok thanks :)
