### ISSUE TITLE
Suggestion: cycle through different paintings of the same size while holding a painting in your main hand and right clicking on the painting which is hanged on the wall

### ISSUE THREAD

**Issue by SepSol** [ArtixAllMighty/Paintings--#29]
title :)

**Comment by ArtixAllMighty** [comment]
say what now ? 
i can read, but it didnt connect in my brain

**Comment by ArtixAllMighty** [comment]
okay so i read itr a couple of times and thought about it. I see what you mean.

Answer : 
you litterally have a Painting Selection Gui integrated into the mod. 
why cycle the paintings if you can litterally pick any size and painting you want with two clicks and some scrolling ?

**Comment by SepSol** [comment]
Because it may help you when you want to compare different paintings of the same size to see if it fits in your build. Take a look at this mod: Cycle Through Paintings

**Comment by ArtixAllMighty** [comment]
I'll ask the author to see if he has any objection if I use the sole feature his mod adds to my own mod.
I'll keep you posted

**Comment by SepSol** [comment]
Thanks

**Comment by SepSol** [comment]
That mod only cycles through default paintings though, it doesn't recognize your paintings.

**Comment by ArtixAllMighty** [comment]
I'd call that bad coding lol. My paintings use the vanilla entity and registry to add onto them.

**Comment by SepSol** [comment]
So hopefully your paintings could easily integrate into that mod's function

**Comment by ArtixAllMighty** [comment]
its rather the other way aorund :P

**Comment by ArtixAllMighty** [comment]
went ahead and added it just in case
https://streamable.com/lnyst

**Comment by SepSol** [comment]
Thanks a lot :)
