### ISSUE TITLE
Suggestion: GUI with paintings' size in it

### ISSUE THREAD

**Issue by SepSol** [ArtixAllMighty/Paintings--#30]
It would be great if the placement GUI which is right now well-organized, showed the exact block dimensions of each paintings or groups of paintings.

**Comment by ArtixAllMighty** [comment]
hmmmmmm......

**Comment by ArtixAllMighty** [comment]
https://streamable.com/zrq0n

**Comment by SepSol** [comment]
@ArtixAllMighty  that number in the bottom is not present for me: [https://streamable.com/auccz](https://streamable.com/auccz)

MC 1.14.4
Forge 28.1.0
Paintings++ 6.0.0.0.0

**Comment by SepSol** [comment]
If the video above didn't work: [https://www.dropbox.com/s/b2jmjgahojj2b2l/Base%20Profile%202019.10.20%20-%2016.10.49.02.mp4?dl=0](https://www.dropbox.com/s/b2jmjgahojj2b2l/Base%20Profile%202019.10.20%20-%2016.10.49.02.mp4?dl=0)

**Comment by ArtixAllMighty** [comment]
That's normal. you just added the suggestion. I just added this in the code. 
I was just showing off that I actually just now implemented your suggestion

**Comment by SepSol** [comment]
Ow, I see
