### ISSUE TITLE
Max Image Dimensions 

### ISSUE THREAD

**Issue by FinnaBe** [ArtixAllMighty/Paintings--#34]
Can we add a comment in the default Paintings.json template along the lines of
max painting dimensions supported are 64x64 or what ever they really are.. I know "square" : 128 does not work.

**Comment by ArtixAllMighty** [comment]
There should be no limit whatsoever

may i see a log and the json file please ?

**Comment by ArtixAllMighty** [comment]
closing issue due to absence of answer. 
feel free to re-open if needed
