### ISSUE TITLE
Max Painting Count?

### ISSUE THREAD

**Issue by Pr0gression** [ArtixAllMighty/Paintings--#35]
Is there a limit on number of custom paintings in the new 1.14 versions?  Crash when I use a large number of images in the paintings folder.

[crash-2020-01-25_12.56.01-client.txt](https://github.com/ArtixAllMighty/Paintings--/files/4112503/crash-2020-01-25_12.56.01-client.txt)

Thanks,

**Comment by ArtixAllMighty** [comment]
there shouldn't be.
Could you provide the json used to load in the paintings ?

**Comment by ArtixAllMighty** [comment]
NegativeArraySizeException points to a negative length of an array / aka list of data.
I'm suspecting your (if you use a custom) json file has wrong or mistyped information in it

**Comment by Pr0gression** [comment]
[custom - Copy.txt](https://github.com/ArtixAllMighty/Paintings--/files/4446669/custom.-.Copy.txt)

**Comment by Pr0gression** [comment]
[custom - Copy.txt](https://github.com/ArtixAllMighty/Paintings--/files/4446680/custom.-.Copy.txt)

As far as I can tell its typed properly but maybe not.

**Comment by ArtixAllMighty** [comment]
could you try cutting out half ? or test just with a painting or ten ? to test if we did reach a limit.

**Comment by Pr0gression** [comment]
I tried with 75 and it works fine with that many

**Comment by Pr0gression** [comment]
Ya I tried adding bit by bit and its at 93 count that it gives the exception

**Comment by ArtixAllMighty** [comment]
ill look into it, thanks for the report !
Could you join my discord for a bit to pass the files and such so i can test it and run it trough with you ?

**Comment by Pr0gression** [comment]
Thanks, sure can do

**Comment by Pr0gression** [comment]
Where would I go for that lol, sorry

**Comment by ArtixAllMighty** [comment]
> Where would I go for that lol, sorry

https://discord.gg/8MEdFZh
