### ISSUE TITLE
Transparency issue

### ISSUE THREAD

**Issue by ArtixAllMighty** [ArtixAllMighty/Paintings--#38]
![image](https://i.imgur.com/f8AYxBZ.png)

**Comment by Foreck1** [comment]
Transparent paintings in 1.12 work but have z-fighting too, I don't know if that can be addressed along with this bug

**Comment by ArtixAllMighty** [comment]
> Transparent paintings in 1.12 work but have z-fighting too, I don't know if that can be addressed along with this bug

I'd advise opening another issue for that, given it is a different version.
Support for lesser versions has been dropped however. but given the popularity of 1.12.2 yet, I may reconsider. but do not accept this as a statement that I will fix it.

as for the transparency issue in 1.15 : i'm working on it. expect a new build soon

**Comment by ArtixAllMighty** [comment]
The bug in 1.15 is caused by Minecraft itself.
I'll be submitting a PR to forge to have painting rendering include transparency instead of it rendering only solid textures
