### ISSUE TITLE
[1.12.2] Transparent and translucent support 

### ISSUE THREAD

**Issue by Foreck1** [ArtixAllMighty/Paintings--#40]
Transparent paintings in 1.12 work fine for the most part but heavy have z-fighting on each "block" border, i.e. each 16 pixels, an artifact in transparent areas of the painting appears.

**Comment by Foreck1** [comment]
Additionally, translucent pixels in png file turn to full opacity in world, thus making it impossible to add shading or window/glass paintings.

**Comment by ArtixAllMighty** [comment]
The z fighting has been a known issue that I have never been able to pinpoint down and fix. 
The translucency is dictated by minecraft and is something I cannot change. (no entities can have translucent pixels as far as i know, unless their renderer does include translucency.)
The mod is just hooking into the minecraft painting entity to allow more paintings.

**Comment by Foreck1** [comment]
I see, that's sad to hear.

**Comment by Foreck1** [comment]
Although this issue is closed. there may be some hope in the future to make it work, thus I present these ideas:

1. Draw pixels perpendicular to the borders so that it appears as they were voxels and it's no longer possible to see the seams every 16x16 pixels.
2. Have an option to separate each painting in the texture file by one pixel from one another, so that frames don't collide with each other at the borders.
3. Check if what [Transparent](https://www.curseforge.com/minecraft/mc-mods/transparent) mod does in 1.15 can be reproduced here..
