### ISSUE TITLE
Crash when equipping painting item, or loading a world in which painting is equipped.

### ISSUE THREAD

**Issue by nuttapillar** [ArtixAllMighty/Paintings--#41]
Whenever I equip a painting in-game, the game crashes with this error: The game crashed whilst ticking player
Error: java.lang.NoSuchFieldError: world

 

And whenever i try to load a world in which I'm holding a painting, I also crash with the same error.

**Comment by ArtixAllMighty** [comment]
got a full crash log ?

**Comment by nuttapillar** [comment]
Sorry, I have since reinstalled forge and all my mods, and now it's working for some reason.
