### ISSUE TITLE
Crash at the start 

### ISSUE THREAD

**Issue by DamienBrittan** [ArtixAllMighty/Paintings--#43]
1.16.4 
https://gist.github.com/DamienBrittan/9acecb36a815c9bdea23eb45c335a21b

**Comment by DamienBrittan** [comment]
fixed after adding optifine ? no info anywhere that i need optifine to use this mod

**Comment by ArtixAllMighty** [comment]
Optifine is NOT a prerequisite to load this mod. 
Thanks for the report.
It seems theres something wrong with reading a json file and it obstructs the mod from being loaded.
Do you have more detail on your setup ? (Forge version, mod version, ...)

**Comment by ArtixAllMighty** [comment]
Failure message: Paintings ++ (paintings) encountered an error during the load_registries event phase
		net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: paintings:joana_d'arc
	
Id recomand using no apostropges in naming your paintings !
