### ISSUE TITLE
Paintings not technically placed by players

### ISSUE THREAD

**Issue by Matthysse** [ArtixAllMighty/Paintings--#45]
Hello!
With a forge+bukkit server jar, we can place paintings in not-allowed areas. But we can't do that with any other entity from any other mod, because it detects that the player placed it. Without the mod, players aren't able to place paintings in these protected areas. But with the mod, players are able to do that. I think it's because your mod is coded in the way that it doesn't say to the server that it is that specific player who placed that entity. Could you make that the paintings placed by players really are placed by the players, just like in the vanilla game?

**Comment by ArtixAllMighty** [comment]
Ill be looking into it

**Comment by ArtixAllMighty** [comment]
I will be removing an anotation that makes the interact event with paintings of my mod of the highest priority. it should solve your issue.

**Comment by Matthysse** [comment]
Okay, thanks! I will try that later when I have time.

**Comment by ArtixAllMighty** [comment]
Hi, have I ever release a new working version ? I forgot ... it's been a while.

**Comment by Matthysse** [comment]
Hello,
No I don't think you released it

**Comment by ArtixAllMighty** [comment]
oh damn, now i feel bad.... 
And i don't have any time to debug and release another version anytime soon :'(

**Comment by Matthysse** [comment]
No worries, that was just a minor bug I found, and for the moment I only play forge alone, it was more something to perfect even more the mod in the future

**Comment by ArtixAllMighty** [comment]
pushed in recent commit
0241942f0d11527e3a02701d94ba4b5e6872a2f5
