### ISSUE TITLE
Configuration file not being generated

### ISSUE THREAD

**Issue by VictinZero** [ArtixAllMighty/Paintings--#46]
A `morepaintings.cfg` file wasn't created even after running Minecraft multiple times. I'm running version 1.16.5 on Forge 36.0.24, I believe. The only other mod I had installed is WorldEdit, and I do have a Resource Pack installed (Faithful 32x32). I even tried Windows' file search to see if it was created elsewhere, but it didn't find anything. Nonetheless, the painting selection GUI works when I place paintings.

Regardless, is it still possible to add new paintings by following the instructions described for Minecraft 1.14, or do I need to edit the configuration file to use Custom Patterns? (That section of the ReadMe is empty.)

**Comment by ArtixAllMighty** [comment]
the config files have changed locations ever since the latest updates. 
they're not in the general config folder anymore but are generated per world.

**Comment by ArtixAllMighty** [comment]
* they are generated separately for client and server, one of them being in the config folder next to the save folder, the other one being in the config folder inside the save folder.
