### ISSUE TITLE
[Feature Suggestion] An option for a "individual item" mode for the paintings.

### ISSUE THREAD

**Issue by Corvus20** [ArtixAllMighty/Paintings--#47]
Implementing an option that makes it so that each painting is its own item, and so that you can only get that painting if you have that item. players cant craft these paintings, but rather find them in chests, on the walls of structures, or as villager/wandering trader trades. This option would give the player a bunch of things to collect if they want a complete art gallery.

**Comment by ArtixAllMighty** [comment]
true, but this mod facilitates the use of vanilla paintings and adds onto that. 
What you described could be an entire other mod, and a fun one at that.
Not gonna be this mod though, sorry.
