### ISSUE TITLE
How to install the mod on forge only server

### ISSUE THREAD

**Issue by BrewishSpermazist** [ArtixAllMighty/Paintings--#49]
Got kind of issue trying to install paintings++ on my 1.12.2 server.
Could not find any guide how to use my own paintings resource pack, where i should place textures. Should I replace assets\subaraki\art\massive.png or create my own resourcepack zip?
Also I painted hi-res _massive_ pattern
![massive4x](https://user-images.githubusercontent.com/81168588/112767063-4b7f0900-901d-11eb-95f3-a807a93a18fb.png)

**Comment by ArtixAllMighty** [comment]
I'm gonna be honest, its been a long time and Paintings++ has gone trough many phases.
I, and other people that helped in the past, have tried to find the best way for people to add paintings. 
I can't for the life of me remember how or what kind of system was used in 1.12.2, I even believe it went trough a phase or two in that version ... 
So either all you can do is switch templates in the config file, or you have to add one trough a resourcepack, and edit / add a json file with all paintings (layout of png, sizes, etc.... )

I'd shoot myself in my foot if I told you to rather not use older versions, So i'm going to suggest to use the latest ? :s 
I'm very sorry for the inconvenience and unprofessional approach for a solution...

Hope you enjoy it none the less :(
