### ISSUE TITLE
Problem with picture

### ISSUE THREAD

**Issue by historianroo** [ArtixAllMighty/Paintings--#50]
After trying forever, I finally got the mod to load with the photos, but the images do not appear properly. Instead of being what I want they are squares that are black and bright pink. Any help would be great??

**Comment by historianroo** [comment]
I use 1.16.5 Minecraft version I believe.

**Comment by Exikeya** [comment]
I got the same problem. Followed the guide on the main page and checked if I did any mistakes, but everything seems right to me. The paintings look fine in the folder, but ingame they're just black and magenta squares.
If you need some more details to find a solution, I will provide them.

**Comment by ArtixAllMighty** [comment]
check the logs, 
your logs probably tell you that non a-Z ./_ characters have been used.

Then check your picture names, and make sure they are correct and correspond to the names given in the json file. 

no spaces can be used. all names must be unique for every picture.

**Comment by Exikeya** [comment]
[23:56:36] [Worker-Main-12/ERROR]: Using missing texture, unable to load paintings:textures/painting/endemic_life.png : java.io.FileNotFoundException: paintings:textures/painting/endemic_life.png

Found this in the log, but don't know, what it means. Sorry I've got no experience with this stuff.

**Comment by ArtixAllMighty** [comment]
file not found means that the given path for the texture can not be located. 
what's the path of your textures in the resourcepack ?

**Comment by Exikeya** [comment]
assets/paintings/textures/painting

The pictures are in the last folder painting.

**Comment by ArtixAllMighty** [comment]
what does your json look like  ?
Also : https://discord.gg/8MEdFZh
if you can join my discord we can exchange files and i can work directly on the issue

**Comment by ArtixAllMighty** [comment]
Turned out to be a pathing issue in the way the resourcepack was constructed. 
if @historianroo still has the issue after trying this fix, he can contact me true Discord on the perma link given above.
