### ISSUE TITLE
SOLVED - Crash at the start - Painting ++(paintings) has failed to load correctly (java.lang.ExceptionInInitializerError: null)

### ISSUE THREAD

**Issue by AlexGrade0** [ArtixAllMighty/Paintings--#51]
[crash-2021-07-30_15.48.43-fml.txt](https://github.com/ArtixAllMighty/Paintings--/files/6908291/crash-2021-07-30_15.48.43-fml.txt)

What I already tried:
- reinstall Minecraft
- get latest forge version
- get latest Paintings ++ version

**Comment by AbsolemJackdaw** [comment]
```java
Caused by 1: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException:
```

do you happen to run a custom painting pack ? or a downloaded one ? If you do, please check your or their painting json file for syntax errors.

**Comment by AlexGrade0** [comment]
Well, i don't have any custom painting packs, but when you said that a resource pack could be causing an error I went to check it , I removed every resource pack that I have and it works now! Probably it's a resource pack that changes the paintings too that is causing this error. I just need to find out which one it is and remove it. Thanks!

**Comment by AbsolemJackdaw** [comment]
Thanks for the report though. 
The mod goes trough all resourcepacks looking for json files with a certain tag in them. 
Ill see if i can somehow read the json files out safer so it doesnt crash. If any one rp has a weird or faulty json this could jeopardize a lot of users and packs

**Comment by AlexGrade0** [comment]
No problem. 
After some time I found the files that were causing this error, do you need them?

**Comment by AbsolemJackdaw** [comment]
It can be of no harm to check them out to maybe prevent wrong readouts in the future. Maybe also notify the mods the jsons came from ?

**Comment by AlexGrade0** [comment]
[ResourcePack.zip](https://github.com/ArtixAllMighty/Paintings--/files/6911706/ResourcePack.zip)
Well, I've had this resource pack for a long time and it was a resource pack that I made by putting together some resource packs, so I don't remember who made them. 
Should I close this issue?

**Comment by AbsolemJackdaw** [comment]
Leave it open, ill close it when im done checking out if theres anything i can do. You can put solved in the title if you want for people with a similar issue passing by :)

**Comment by AbsolemJackdaw** [comment]
in the json files 
bow_pulling_2.json
bow_pulling_1.json
bow_pulling_0.json

you have a syntax error, there's a semicolon '}' too much.

the resource pack reading does skip a beat when finding any error in json files, and then just skips over the entire process.
make sure all json files are parsed correctly and present no errors.

The errors only were visible after I extracted the compressed filed and repacked it as a zip file. 
Before that, it threw some kind of error about not finding the end stream of the zip file, which indicate that it may have been a renamed .rar file or other compressed format. 
.zip reading and parsing Json files is a finicky process and throws crashes and temper tantrums at you when one thing's off. 
make sure to be careful in the future !
