### ISSUE TITLE
Breaking paintings in 1.12

### ISSUE THREAD

**Issue by ArtsyDy** [ArtixAllMighty/Paintings--#52]
New problem I realise 1.12 here. When closing Minecraft and opening again, going to back world, the paintings start invisible then immediately break.
I should note, i'm trying to get it into RLcraft, so there might be some sort of mod conflict that i'm unsure of.
The problem isn't caused unless I close and open RLcraft again.

**Comment by ArtsyDy** [comment]
I just tried it in vanilla, and it still breaks so it's not a conflict with RLcraft.

**Comment by AbsolemJackdaw** [comment]
1.12 isn't supported anymore. 
I don't have an answer on it either, because you're the first one to report it in the five years the mod existed since 1.12
(yes 1.12 is five years old ! :o )

**Comment by ArtsyDy** [comment]
Hmm is there any chance there are even older versions of it that might work? Thats probably a stupid question admittedly but im grasping at straws XD

**Comment by AbsolemJackdaw** [comment]
https://www.curseforge.com/minecraft/mc-mods/paintings/files/all?filter-status=1&filter-game-version=1738749986%3A628

anything from this list on the official mod page should work

**Comment by ArtsyDy** [comment]
I'm filled with glee, the version before the one I used actually works for some reason. Thanks.
