### ISSUE TITLE
custom paintings not showing

### ISSUE THREAD

**Issue by Dawriter** [ArtixAllMighty/Paintings--#54]
I followed the directions to create my custom resource pack. I added it to my game and enabled it and my painting did not show up in the selection. I do have a json file that follows what you laid out. I also tried one of the resource packs you have listed as compatible to see if that would work: Brewing Canvas. The paintings from this resource pack also did not show up in the selection. I am using the 1.18 version of the mod. Can you think of what might be going wrong for me?

**Comment by AbsolemJackdaw** [comment]
found a solution ? 
what was the issue ?
