### ISSUE TITLE
No Datapacks Paintings Will Load Textures Anymore

### ISSUE THREAD

**Issue by RotokEralil** [ArtixAllMighty/Paintings--#57]
I stated up minecraft today and my paintings all show started to show up as missing textures.
I removed all mods except dependents and paintings and created a new world, and took turns trying out the baroque and ren pack, the brewing pack, even the extraalchemypack, and none of them will show anything.

![Untitled](https://user-images.githubusercontent.com/96855797/149615580-7d3caee9-4dfa-47f5-a552-1a6bb532372e.png)
[BrewingCanvas_v0.6_1.18.zip](https://github.com/ArtixAllMighty/Paintings--/files/7874583/BrewingCanvas_v0.6_1.18.zip)
[latest.log](https://github.com/ArtixAllMighty/Paintings--/files/7874586/latest.log)

**Comment by AbsolemJackdaw** [comment]
Hi ! 
I've got some extra questions: 
What version are you using ? 
What loader are you using ? (forge/fabric)
Is this an existing world ? or a new one ? 

a pre-emptive conclusion I can make is that: 
a) your paintings are being registered. so the json out of the resourcepack is being read correctly
b) your textures arent showing up for the recognized paintings. > have you made sure you loaded your resourcepacks in the game ? trough the resourcepack gui ?

**Comment by RotokEralil** [comment]
For some reason, minecraft removed all of my resource packs from my base world (which were only paintings, hence why I didnt notice). And since I was recreating a new world based off the old one, it did not include any of the resource packs, which explains while they didnt show in new worlds.
Sorry for the trouble, looks like it was Conclusion B.

**Comment by AbsolemJackdaw** [comment]
No problem ! Enjoy :D
