### ISSUE TITLE
Animated paintings show up squashed in GUI 

### ISSUE THREAD

**Issue by Skeithh** [ArtixAllMighty/Paintings--#58]
There's a tiny issue that when you have an animated painting (which will have a larger image for the frames), it shows up kind of funky and squashed in the GUI. If its possible for the GUI to maybe be set up so that it only takes the first frame of the painting, that'd be great.

example:
![image](https://user-images.githubusercontent.com/74820899/149836370-0e3016f4-4d58-4683-8feb-10a1a9e6b3a6.png)

**Comment by AbsolemJackdaw** [comment]
aren't animated paintings an optifine thing ?

**Comment by Skeithh** [comment]
nope! they are possible in vanilla. All you need is an .mcmeta file to tell it to be animated

**Comment by AbsolemJackdaw** [comment]
okay, ill see what i can do. may take a while, exams are around the corner.

**Comment by Skeithh** [comment]
No worries, its not an urgent thing now that I know what im supposed to look for to find my animated paintings. if it helps- 
the way that the animation mcmeta file looks like is more or less what i attached here.
![image](https://user-images.githubusercontent.com/74820899/149841113-b027e52b-a4e3-468f-8e77-36655adb2cff.png)

ideally it could just look at frame 0 (if the "frames" field is present) and otherwise display the squashed image.

**Comment by AbsolemJackdaw** [comment]
![image](https://user-images.githubusercontent.com/3628535/167726466-f2681a7c-50c3-4366-8ea7-88554ea6953c.png)

i managed to find a way. there will be a new possible option to put in painting data in the json file
anim will now serve to tell how long the animation file is, x and y what the size of the visible painting should be.
the animation will not be handled by the gui, but should then be handled in-world by minecraft itself.

i hope this pleases you :D
