### ISSUE TITLE
Failed to synchronize, new join to LAN world

### ISSUE THREAD

**Issue by Halibear** [ArtixAllMighty/Paintings--#61]
I have been playing a world for quite some time and recently someone new tried to join on a LAN connection (brand new computer so I literally copy pasted my entire mods/resource pack/config folders). I can join a new world of theirs and they can join a new world of mine, but when they try to join this world we get the failed to synchronize registry data from server error. When I looked at the log it pointed to paintings, so I removed it and they can join.

What folders should I verify are matching? I'm assuming this is an easy fix that's on my side, any help is appreciated! :)

**Comment by AbsolemJackdaw** [comment]
Im going to need the log, mc version , and modloader to be able to help.
Thanks for the report !

**Comment by Halibear** [comment]
forge-1.18.1-39.0.76 & .75

... let me see if I can find that log, once we figured it out we started playing, LOL!

**Comment by Halibear** [comment]
I'll have to wait for them to get back over to my house and we can recreate the log, sorry I should have known better to just copy it at the time.

**Comment by AbsolemJackdaw** [comment]
The only thing i can make out so far is that the resourcepacks dont match with the old world. The only reason there would be a registry mismatch is when the painting json isnt read out correctly and one of the games doesnt register the paintings accordingly...

The log should be present. Old logs are zipped up and stored in the log folder.

**Comment by AbsolemJackdaw** [comment]
closing stale issue. 
Considered resolved trough lack of answers.
Issue can be reopened if needed
