### ISSUE TITLE
Issues Using with Minecraft Forge 1.18.2 Paintings

### ISSUE THREAD

**Issue by PawInspector** [ArtixAllMighty/Paintings--#64]
After struggling for some time getting the mod working in general, I am now experimenting with it myself.

The tutorial instructs creating a resource pack with the file structure:
    `> assets/paintings/textures/painting`

which works independently with the mod. However, I tried using this in conjunction with the conventional method of creating a resource pack with custom paintings -- by renaming the vanilla Minecraft paintings and putting them in the painting directory in a resource pack. The painting directory for Minecraft 1.18.2 (I don't know when it started but this is the current version I am using) is as follows:
     `> assets/minecraft/textures/painting`

Long story short, in my experimentation, I now have three different versions of my resource pack trying to figure out what was wrong and why I was receiving missing textures.
- One instance uses the vanilla Minecraft directory with custom vanilla paintings as well as additional paintings. With this, the retextured Minecraft paintings appear, but the added/modded paintings do not (which I'm sure is obvious to you, seeing as how you specified the directory to use), but,
- the second instance uses the directory you suggest, `> assets/paintings/textures/painting` and, unsurprisingly, the added/modded paintings appear, but the resource pack no longer affects the retextured vanilla-named paintings. And, so,
- I created a third instance (alternating all of these out one by one, of course) with both directories within the assets folder, `> assets/minecraft/textures/painting` and `> assets/paintings/textures/painting`, figuring this would be a simple fix. Each directory has the corresponding painting textures -- the Minecraft directory has only the renamed Minecraft paintings, and your directory contains only the added/modded paintings. Trying to activate the resource pack like this, however, causes Minecraft to fail to load the resources in general, all of this testing is with Minecraft running, and trying to load this version I receive a Toast notification that says "Resource Reload Failed".

Does this mod work with the current Minecraft version, 1.18.2, painting directory? Is there something I can do to make them work side-by-side?

I am running Minecraft Java Edition 1.18.2
Forge version 1.18.2-forge-40.0.22
Other mods I'm running:
 - Optifine_1.18.2_HD_U_H6
 - Xaeros_Minimap_22.3.1_Forge_1.18.2
 - XaerosWorldMap_1.20.4_Forge_1.18.2
My resource pack is updated to the current version of Minecraft's resource packs (I tried changing the paintings before finding this mod, this that's already updated).
Lastly, I'm running Windows 10 21H1 build 19043.1586

I hope this is enough information.

**Comment by AbsolemJackdaw** [comment]
Hi ! 
This is an interesting issue. First time I hear of it !

I just tested this by replacing the wanderer painting and with a test pack I got laying around. 
Both folders are in the one resourcepack zip, but everything is working fine. 

Could you try running your 'dual' pack again, but without optifine installed ?
Optifine is the root of a lot of issues in the modding community... 

If it still doesn't work, I'd love for you to post the latest.log, so I can try and figure out what exactly the game doesn't like in (re)loading the resources.

**Comment by PawInspector** [comment]
I tried running it without Optifine and it was the same thing. I also was doing some reading into the latest.log file to see if I could figure anything out and all I did was make a few changes (like resizing images (when that was never a problem) and learning that Minecraft is case sensitive all the way down to the resource packs...) and it was still the same outcome. I even carried over these changes to the separate packs and tried them individually again and they still work the same.

If it's working for you, then could I ask what are you doing? It must be that I misinterpreted how I could combine the two file locations or something since I don't actually know what I'm doing. (All I do know is if I send you the lastest.log file, I'll have to change a bunch of file names...for your sake >-< So I'm hoping to not have to do that just yet.)

**Comment by AbsolemJackdaw** [comment]
I just put an edit of the wanderer .png inside assets/minecraft/textures/painting, and one image in assets/paintings/textures/painting, and a json file with the info on top level.
if you open the zip, you can see the mcmeta, json file, and assets folder. in the assets folder you got minecraft and paintings folder.

you can just post your log, no need for edits. I'm old enough and I'm pretty sure I have seen enough to not be shocked by the titles of your paintings.

**Comment by PawInspector** [comment]
Oh, gosh, well...

I tested out what you did in a fresh, new resource pack, one picture in each folder, and you're absolutely correct! That works just fine! So, now...that makes me think there's something wrong with one of the pictures in particular so I guess I have no other choice but to share the log file. This run has Optifine in it because I tested without and with it.

And, again, if you say you're ready for it, the names go from zero to 110 very quickly >.<
[latest.log](https://github.com/ArtixAllMighty/Paintings--/files/8337425/latest.log)

**Comment by PawInspector** [comment]
Oh, I think I fixed it. I'm so glad I sent you the log for no reason! Sorry about that!

I can't quite say I know why this was the problem, so I'll tell you what happened to see if maybe you know why. After my previous revelation that it must be one of the pictures, in particular, that was messing things up, I started testing each picture individually.

Again, I think it's weird because each version of the resource pack worked individually -- version 1 with both retextures and modded in assets/minecraft/textures/painting showed only the Minecraft retextures; version 2 with both retextures and modded in assets/paintings/textures/painting only showed the modded paintings; both instances showed all of the paintings with no trouble...regardless of size!

In this version 3, both folders are in the assets folder (assets/minecraft... and assets/paintings...). Long story short, I narrowed the problem down, surprisingly, to being a picture in the Minecraft retexture folder. Again, long story short, I narrowed it down further and further until I found that wanderer.png (ironically the picture you tested!) was the culprit causing the issue. Yet again, I don't know why because it didn't cause a problem before, but the only thing I could think to do was resize the image, so I did so by 50% and now the whole resource pack works. I even took it a step further and downloaded a transparent paintings resource pack for one of the paintings I have and it works with that as well! I don't know if there's a size limit to resource packs or something because I ended up resizing a bunch of pictures before getting this whole thing to work...but _again_...THEY ALL WORKED INDIVIDUALLY WITHOUT NEEDING TO BE RESIZED!

I spent way too long trying to figure this out... >-<

**Comment by AbsolemJackdaw** [comment]
They do have a limit. The limit is your graphics card capability of handling the size. The textures get stitched together by the game in an atlas. 

I suggest trying Pinga do reduce file size. It cuts out metadata and redundant info out of images :)
Apart from that, i could t really tell what else could be an issue
