### ISSUE TITLE
Painting pack not loaded on 1.18.2 server

### ISSUE THREAD

**Issue by fujcycle13** [ArtixAllMighty/Paintings--#66]
Paintings++ 1.18.2-9.1.2.0
Forge 40.1.0

* Added the "RenaissanceAndBaroque1.18.zip" to the server /resourcepacks.
* Extracted the "RenaissanceAndBaroque.json" out of the zip and into the server /paintings.
* Added the "RenaissanceAndBaroque1.18.zip" to the client /resourcepacks. (paintings load properly in singleplayer)

Error in server logs when loading and no paintings from pack shown in server:

13.05 15:33:01 [Server] modloading-worker-0/WARN [paintings/]: ************************************
13.05 15:33:01 [Server] modloading-worker-0/ERROR [paintings/]: Invalid ResourcePack  RenaissanceandBaroque1.18.zip
13.05 15:33:01 [Server] modloading-worker-0/ERROR [paintings/]: zip END header not found
13.05 15:33:01 [Server] modloading-worker-0/WARN [paintings/]: ************************************

**Comment by AbsolemJackdaw** [comment]
the renaissance and baroque resourcepack seems to be having some issues. 
please contact the creator of said resourcepack so they can update their pack ! 

You could also read trough the latest.log to see what kind of issues the pack has.

**Comment by AbsolemJackdaw** [comment]
the error shown means that it is not recognized as a proper zip file btw
you may want to unpack the contents and make a new zip file out of it. .rar doesnt work

**Comment by AbsolemJackdaw** [comment]
marking this as resolved due to time and lack of response
