### ISSUE TITLE
can't get custom paintings to show up, 1.18.2

### ISSUE THREAD

**Issue by Telekia9691** [ArtixAllMighty/Paintings--#67]
I have been trying to follow your instructions on how to make a resource pack for the custom paintings for like an entire day almost, but for some reason it just will not work, the mod seems to work since the paintings that come with the mod work.

**Comment by AbsolemJackdaw** [comment]
If you upload the pack i can take a look at it

**Comment by Telekia9691** [comment]
[pack.zip](https://github.com/ArtixAllMighty/Paintings--/files/8705477/pack.zip)

**Comment by AbsolemJackdaw** [comment]
First glance it looks like you have used capital letters, which you cannot.

You could refer to your latest.log to check for errors, the mod should do a great job of tzlling you exactly what went wrong. 
In this case it probably printed "character issue, none [a-z0-9./-] character found" or something in the likes :)

Pretty sure its also stated on the tutorial you can only use lower case letters and not capital letters.

**Comment by Telekia9691** [comment]
oh I see I must have missed that, my bad. thank you for a very quick response.
