### ISSUE TITLE
Not working in 1.12.2

### ISSUE THREAD

**Issue by JiayangLi-7** [ArtixAllMighty/Paintings--#68]
I created a folder like this:
  -Painting++
      --assets
          ---subaraki
              ----art
                  -----gibea.png
              ----patterns
                  -----gibea.json
      --pack.mcmeta

Paintings++ mod for 1.12.2 and this resource pack are both activated, but I can't find any additional painting in game. What should I do? Or is 1.12.2 not supported anymore?

**Comment by AbsolemJackdaw** [comment]
Painting packs with json are a 1.14+ feature.
For 1.12 you need to pick a template layoute in the comfig file and add your paintings to the template. 
The wiki has this explenation somewhere.
I forgot if there's a 1.12 tutorial that survives, but you can always look.
Support for 1.12 is sparse indeed, if not completely absent

**Comment by JiayangLi-7** [comment]
Thank you for answering! This mod is exactly what I need so I really want to figure out how it works

The only tutorial I found on the wiki was about making resource pack :P

So...just need to replace those templates in the mod for 1.12.2?

**Comment by AbsolemJackdaw** [comment]
better practice is to make a resourcepack that overwrites those templates present in the mod.
the config can be used to switch over to the template you want to use

**Comment by JiayangLi-7** [comment]
It works! Thanks a lot!!!
