### ISSUE TITLE
Not displaying paintings

### ISSUE THREAD

**Issue by Mohotzgui** [ArtixAllMighty/Paintings--#69]
Hello,

I've been using this mod forever, I have a huge pack that works on Forge perfectly. I am trying Fabric 1.19.x and though the mod works it is not reading the json file for the paintings. It doesn't read any paintings for any other mods either like it does in Forge. Is there something special on fabric?

**Comment by AbsolemJackdaw** [comment]
_normally_ fabric should have the same mechanics as Forge.
I'd like to see a latest.log please, so I can check what went wrong.

**Comment by Mohotzgui** [comment]
Here is the link to the PasteBin https://pastebin.com/00zYJKfp

**Comment by AbsolemJackdaw** [comment]
Sorry, I've been a bit busy.
the mod doesnt seem to be listed in the log ? 
the mod equally prints out a some logging when it registeres paintings, which i'm not seeing at all.
May it be you forgot to add the mod or gave me a wrong log ?

**Comment by Mohotzgui** [comment]
Other than that log I'm not sure of others. The mod itself appears to be running, the GUI comes up when placing a painting but it only displays the paintings from the actual game not the MOD or the resource pack I made for it, this has only been in 1.19 for fabric, all other forge and fabric versions have worked. I will try just removing it all and reinstalling it and see if that works.

**Comment by AbsolemJackdaw** [comment]
Ive just tested with a clean instal on my curseforge app, darkpaintings mod and the oliver remund painting pack on fabric

they all show up.

did you by any chance remove the shipped painting json from the painting fodler that the mod automatically places in the painting folder in your install directory ? 
is your self made resourcepack not containing any errors ? zipped up ? can you share the zip file so i can check it ?

**Comment by AbsolemJackdaw** [comment]
issue 20 days old with no reply after author made a suggestion of a change/edit on his end. 
Issue will be flagged as resolved by author on their end.
Closing this issue
