### ISSUE TITLE
Sample File?

### ISSUE THREAD

**Issue by PrinceAllart** [ArtixAllMighty/Paintings--#70]
I'm trying to use this mod with forge, minecraft ver 1.12.2, and the game recognizes the resource pack but when I load into a world the only paintings that come up to be chosen from are the original minecraft ones. I went over the tutorials but feel like I'm missing something important. Is there a sample file I can compare mine with so I can figure out what needs to be fixed?

This is my first attempt at modding minecraft but I've worked with json files in other games before. I've attached my current resource pack. It's not complete, as I have many more paintings to add but I was trying to test it. I also do not plan to share this with anyone other than my son.

Thank you

[ALs_Paintings_Resource_Pack.zip](https://github.com/ArtixAllMighty/Paintings--/files/9088763/ALs_Paintings_Resource_Pack.zip)
.

**Comment by AbsolemJackdaw** [comment]
that pack would work great in 1.14 and up ... 

for pre 1.14, check this out 
https://github.com/ArtixAllMighty/Paintings--/wiki/Art-Files

1.12.2 used template files. 
minecraft 1.14 had internal changes, allowing me to make them separate files

I'd advice to update to a later minecraft version either way, but making a pack for 1.12 is still viable, all be it a bit more work

**Comment by PrinceAllart** [comment]
You know what's funny? I had started using the templates and then stopped when I read the instructions saying they could be separate. Anyway, thank you for your prompt response. I'll look into this and try it this way.

**Comment by PrinceAllart** [comment]
I still can't get the paintings to show up. I tried using one of the templates and then I tried making my own. I can't get anything to show up. Is there something I need to do with the mod itself?

Thank you again for your assistance.
[allarts_paintings_1.12.2.zip](https://github.com/ArtixAllMighty/Paintings--/files/9108349/allarts_paintings_1.12.2.zip)
?

**Comment by PrinceAllart** [comment]
Okay, I am able to get it to load under gibea but not my custom pattern and image. I've changed the config to the name of the pattern but they will not show up. Is adding patterns now allowed in 1.12.2?
Even if I can figure the custom pattern thing out, at least I can use one of the pre-installed ones and get it to show up
[assets.zip](https://github.com/ArtixAllMighty/Paintings--/files/9117148/assets.zip)
![image](https://user-images.githubusercontent.com/109120805/179133629-12d81558-66d0-461b-989f-daa3a51319b0.png)
.

**Comment by AbsolemJackdaw** [comment]
adding patterns should be allowed in 1.12 :/ but its been so long, i forgot how to. the config seems to be straight forward about it. 
does the log say anything about the pattern failing ? 
I had worked together with someone else back in the day, and they made the pattern logic, so I can only guess how it worked today. 

you send me the assets zip, but i'm going to conclude those are from another zip where they are in src/main/resources ?

**Comment by PrinceAllart** [comment]
Maybe the issue is I'm using forge? My kid has a custom mod pack he uses and I've been adding this mod and the resource pack to that instance's folder. I cannot find a folder called "src/main/resources"

**Comment by AbsolemJackdaw** [comment]
1.12 is only available for forge , so that's not the issue.
i used to have a 1.12 tutorial but it got lost to time
the issue is probably just that you're using an obscure version where i forgot all details about.

the best option i can think of so far is using one of the default templates and using a resourcepack to change the texture
i'll try poking around the internet to see if i can find another 1.12.2 painting pack somewhere to try and figure out what was going on, but i doubt i'll find any. 

with the path i meant inside of the resourcepack. 
so there should be a folder 'src' inside your zip, with all the subfolders.
i believe... I'm just reading the ocnfig at this point x)

**Comment by PrinceAllart** [comment]
I'm not having any luck finding a resource pack for paintings plus plus mod, ether. What I have done is I used https://www.mcpaintings.com/ and made a test-template pack. That worked but only for replacing the vanilla textures, not adding more paintings. 
I tried adding "src/main/resources" folders to my resource pack but still nothing. So it was src/main/resources/assets/subaraki/ and from there, there are three folders; art, lang, patterns. 

What I find odd is when I change the config information to a different pattern, minecraft just defaults to the original minecraft paintings. The GUI is loading just fine but I have a feeling it's not picking up the rest of the mod. 

I'm not giving up, though and you really are most kind to still help even with something this odd and old. I appreciate it greatly.

**Comment by PrinceAllart** [comment]
I been trying different things out and it appears to be the patterns are not loading, even the built-in ones.

```
[01:07:41] [Client thread/ERROR]: Failed to read "new_insane".json. Make sure the pattern exists in an imported resource pack and is correctly identified in the configuration.
System Message:
subaraki:patterns/"new_insane".json
```

**Comment by AbsolemJackdaw** [comment]
its weird its looking for "new_insane".json instead of new_insane.json

i'll be picking up a 1.12.2 copy this evening to try out some stuff for you.
i generally dont do this, but you've been very udnerstanding and patient and torough in your own research

any chance you could upload your pack here so i can use the images as a reference?

**Comment by PrinceAllart** [comment]
Thank you. From the sounds of it, I'm doing something wrong but I don't know what.  I've been testing out things using this:
[ALsPaintings_test.zip](https://github.com/ArtixAllMighty/Paintings--/files/9126090/ALsPaintings_test.zip)
.
I'll definitely make a tutorial video once we nail this down. And again, thank you for all of this.

**Comment by PrinceAllart** [comment]
Ok, so I deleted the quotations around the pattern name and now it works! 
![paintingsworked](https://user-images.githubusercontent.com/109120805/179369037-6399049b-2416-4d13-937a-703bd7c01028.png)
my custom pattern doesn't work but I think it's my fault as it said there was an error with a specific line of the json file I created.
![patternbroken](https://user-images.githubusercontent.com/109120805/179369156-f61f9d27-e26c-4a8f-91ec-0fac29cd380c.png)

I'm okay with closing this ticket. I'm happy to have anything work at this point, so I call it a win! I'm still going to work on getting the custom pattern to work. Once I do, I'll make a youtube video that you're more than welcome to link to.

**Comment by AbsolemJackdaw** [comment]
that's great ! 
pelase do share the tutorial if you find out everything. 
dont hesitate to ask questions so i can try and recall stuff from memory to help. ive got a discord you can join if ever. 
you makign and sharing a tutorial will probably help more people then you could imagine

**Comment by PrinceAllart** [comment]
I will definitely do that. Might be a few days but In case it helps anyone else, remove the quotation marks in the config file when assigning a pattern. 
Also, it doesn't need `src/main/resources` folders, just the `assets/subaraki/` path with art, lang, and patterns folders within.
![image](https://user-images.githubusercontent.com/109120805/179372893-391617db-900e-4b84-8142-1cbc98403afd.png)
