### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by KallMeKage** [ArtixAllMighty/Paintings--#71]
I looked at the issues and couldn't find the same issue I have, I'm sorry if you've already solved it and I just missed it.

[crash-2022-07-26_20.54.34-fml.txt](https://github.com/ArtixAllMighty/Paintings--/files/9194954/crash-2022-07-26_20.54.34-fml.txt)

**Comment by AbsolemJackdaw** [comment]
nah, forge has had some breaking changes recently, both in .62, .94 and .105
I'm going to have to update the mod again

**Comment by KallMeKage** [comment]
Okay, thank you! For the response I mean

**Comment by AbsolemJackdaw** [comment]
i have updated to forge 1.19-41.1.0
this should solve the issue
