### ISSUE TITLE
Texture loading issue

### ISSUE THREAD

**Issue by Gabuwuw** [ArtixAllMighty/Paintings--#72]
I downloaded the mod for [1.19 fabric] and some textures do not appear, not only that but also many other textures that i saw encoded are missing...

![image](https://user-images.githubusercontent.com/71081782/183312553-e0fa3d56-ac3b-4701-9c38-7928ebbe7df4.png)

The problem is not serious until i realized that i cannot access servers thanks to that problem

![image](https://user-images.githubusercontent.com/71081782/183312880-697b1e34-9dde-434e-95f4-9216fe29cf43.png)

It should be noted that i have not modified the mod since i downloaded it and the other mods im using don't interfere with the Paintings++ mod, also first of all thanks for helping me :( I don't know if this problem happens to everyone, and sorry for the bad english that I am with the direct translator.

**Comment by AbsolemJackdaw** [comment]
Are those custom paintings ? 
Did you edit the json file that is placed in the install directory in a folder called paintings ?

Could you upload the latest.log please?
Paintings++ is not a client sided mod, both server and client need the mod installed, with the same registry of paintings.

**Comment by Gabuwuw** [comment]
The paintings are the default ones (they are not customized) and i have not modified any json file or the paintings folder, i send you the last log.

[latest.log](https://github.com/ArtixAllMighty/Paintings--/files/9279173/latest.log)
(I repeat, no mod has incompatibility)

**Comment by Gabuwuw** [comment]
I did a test removing all the other mods to verify that the problem was not compatibility, there is everything you need for you to see.

![image](https://user-images.githubusercontent.com/71081782/183531798-c21ccf72-21ec-4a9c-a44b-3c368123e9e1.png)
![image](https://user-images.githubusercontent.com/71081782/183531816-011bacda-5c79-41d6-b0a5-4e0f5bf7b64f.png)
And the latest log
[latest.log](https://github.com/ArtixAllMighty/Paintings--/files/9285575/latest.log)

**Comment by AbsolemJackdaw** [comment]
The log mentions custom paintings, none of these are paintings shipped by the mod

![Screenshot_2022-08-09-08-56-00-34](https://user-images.githubusercontent.com/3628535/183584897-a8d6776d-528c-4b01-a39c-2550d21af2d8.jpg)


It therefor cannot find the images

![Screenshot_2022-08-09-08-58-36-45](https://user-images.githubusercontent.com/3628535/183584994-31fa54af-a7f3-4ae3-91e7-bff3967ead75.jpg)

If you didnt get your mod from curseforge then you downloaded a modifed mod from another website.
If you did download it from curseforge, then the base paintings got edited or deactivated, and no resourcepack was provided to provide the images

**Comment by Gabuwuw** [comment]
I downloaded the mod directly from curseforge, and how can i "activate" the base paints and where are those custom paints that appear in the last.log? so i can remove them.
Thanks :(

**Comment by AbsolemJackdaw** [comment]
Good question, this is a first for me too.
Ill have you hop by the discord server so we can solve this together rather then over the ticket. 
https://discord.gg/8MEdFZh

**Comment by Gabuwuw** [comment]
I already found the problem, what happened is that every few months I am inserting and removing different mods, among them modpacks that create folders and docs, among those residual files of an old mod and that I do not know there was one that created incompatibility, simply delete the data from the .minecraft folder and i reinstalled them with paintings++, thanks for your attention, it gave me the data I needed to fix my problem
![image](https://user-images.githubusercontent.com/71081782/183721774-514d4405-218a-468f-ac1d-b96d2241c6a8.png)
