### ISSUE TITLE
Missing Textures 1.18.2

### ISSUE THREAD

**Issue by ATJonzie** [ArtixAllMighty/Paintings--#73]
The pack only shows when unzipped in the gui, however the paintings show up as missing texture
[latest.log](https://github.com/ArtixAllMighty/Paintings--/files/9295082/latest.log)
.

**Comment by AbsolemJackdaw** [comment]
optifine might be the culprit here

**Comment by AbsolemJackdaw** [comment]
one of the issues can also be that your pack ahsnt been added to the game. the json for paintings is read but there's no textures for them to be found. 

to add the textures, makes sure the pack is on the right side of the resourcapack gui interface in game !
