### ISSUE TITLE
Paintings++ Mod gives me an issue saying it has failed to load correctly for 1.19

### ISSUE THREAD

**Issue by ItsKondz** [ArtixAllMighty/Paintings--#74]
![image](https://user-images.githubusercontent.com/109123759/184551925-b10d737b-6e48-46dd-9930-707480baa33a.png)

**Comment by AbsolemJackdaw** [comment]
Update your p++ or downgrade forge

**Comment by ItsKondz** [comment]
It's the latest update of 1.19 (Not 1.19.1 nor 1.19.2)

**Comment by ItsKondz** [comment]
Welp I guess i won't be able to fix it

**Comment by AbsolemJackdaw** [comment]
i'm currently on summer break, i'll take a look at it as soon as i can. 
EntityJoinWorld event is a new Forge Class, 
i forgot what version p++ was coded udner, but its gotta be either prior to forge 94 or after 94

as stated before, tyr to use another forge version. 
you haven't stated yet which forge version you used, which may help me out finding an answer without having access to the code

**Comment by AbsolemJackdaw** [comment]
closing this issue as resolved. 
solution was given, and 1.19.2 has rolled out and is more stable
equally, using a lower forge version may fix this issue
