### ISSUE TITLE
[fabric] config option not working

### ISSUE THREAD

**Issue by AbsolemJackdaw** [ArtixAllMighty/Paintings--#75]
[SkrabyZ ]()
Posted Jul 28, 2022
[#435](https://www.curseforge.com/minecraft/mc-mods/paintings?comment=435)
Using the fabric version for 1.19, changing the setting in the mod config file to to only allow vanilla paintings does not work. All of the mod's custom paintings are still available in the gui. I was really hoping to be able to use this on my vanilla world because there are no other paintings gui mods or datapacks that work and the totally random system in vanilla is just complete garbage.

**Comment by strikerrocker** [comment]
Fixed in version 10.2.3.0
