### ISSUE TITLE
Custom painting pack causes crash

### ISSUE THREAD

**Issue by Hastagaspatcho** [ArtixAllMighty/Paintings--#76]
Mc version: 1.18.2
Mod version: 9.1.2.1
Forge version: 40.1.74

I'm trying to make a custom resource pack for extra content and I cant seem to get the paintings portion working properly. Is there a limit to the amount of paintings you can add? The pack currently has 417 added paintings.

crash log is as follows:
https://pastebin.com/JGs7Uxyq

**Comment by AbsolemJackdaw** [comment]
There is virtually no limit, only your graphics card will be the limit.
Can i see your latest.log too ?
This log says something is wrong with a registry id, which makes me believe maybe one of your painting names might be formatted wrong, but i cant be sure till i see the latest.log

A copy of your pack so i can debug it would be nice too

**Comment by Hastagaspatcho** [comment]
Fair enough, I did run it through the json checker and it didnt come up with any errors but either way, heres the log:
[latest.log](https://github.com/AbsolemJackdaw/Paintings--/files/9440586/latest.log)
and the resource pack in question stripped down to just the paintings (it also wont work as is)
[pack.zip](https://github.com/AbsolemJackdaw/Paintings--/files/9440589/pack.zip)
to specify I did test it with just paintings++ and the transparency mod installed to see if it was a mod conflict and it was still crashing.

**Comment by AbsolemJackdaw** [comment]
there's two paintings called ghost and two called skeleton

names are used as ID for registering paintings, and they cannot be duplicates.
i can remember p++ shipping a painting that's called ghost, so some other pack also adds a painting called ghost.

there's tools for pack makers to not use the base directory of paintings but rather a custom one, so i'm going to shove the issue to the painting pack maker here.
that or they can edit the name of the painting

looks like the beeps pack has those duplicate id's

**Comment by Hastagaspatcho** [comment]
Many thanks for the help, swapping the names fixed it completely.
