### ISSUE TITLE
[1.19.2, Fabric] First painting in json *crash*

### ISSUE THREAD

**Issue by TheSnowyChickens** [ArtixAllMighty/Paintings--#77]
Hello,
I had a time with working custom paintings, but now I am hardstuck.

I get a crash with the first entry in the paintings.json, everytime I start MC and even If I remove the issued painting, I get a new crash with again the first entry.

![grafik](https://user-images.githubusercontent.com/29357962/188499650-951c7786-ab71-444a-b3fd-80bbc7edb68c.png)

I really have no idea what I am doing wrong, all the files are the same, all the names are the same and the files in the "paintings" folder in the minecraft instance folder are the same.

Resourcepack:
[example_resourcepack.zip](https://github.com/AbsolemJackdaw/Paintings--/files/9491575/example_resourcepack.zip)
(and yes, some pictures are from "DarkPaintings" mod, but with your mod and this way to install pictures, I save me 2 more mods in the pack later (atm I only use a tiny test pack))

Crash Report:
[crash-2022-09-05_20.12.51-client.txt](https://github.com/AbsolemJackdaw/Paintings--/files/9491570/crash-2022-09-05_20.12.51-client.txt)

Logs:
[latest.log](https://github.com/AbsolemJackdaw/Paintings--/files/9491572/latest.log)

MC: 1.19.2
P++: 10.2.0.0
Transparent: 1.7.1 
Fabric: 0.14.9

-----

Oh and, I can't join a server, because:

![grafik](https://user-images.githubusercontent.com/29357962/188500259-bbdae9c4-1526-4224-9752-e1b7acec94c1.png)

Pls help me. xD

**Comment by AbsolemJackdaw** [comment]
installing darkpaintings is 100% compatible with paintings++ and easier to use then putting them in a resourcepack. please do use darkhax's mod instead of extracting the paintings out of it ! 

if you need to join a server, the painting registry between client and server needs to match. the servers you join need to have the same paintings installed. 

all your paintigns seem to load fine, or so says the log at least. 

what made you determine following statement ? 
> I get a crash with the first entry in the paintings.json,

currently investigating

**Comment by TheSnowyChickens** [comment]
I had another picture in the first slot of the json, because it crashed I removed it and now the second (now first in the list) picture crash the game.

**Comment by AbsolemJackdaw** [comment]
![image](https://user-images.githubusercontent.com/3628535/188501731-53c10f93-c75d-494e-ab64-7568bd5cb51b.png)

this is why it is better to just use plug and play ...

you have a double entry. duplicate names aren't allowed.

**Comment by TheSnowyChickens** [comment]
oh xD

**Comment by TheSnowyChickens** [comment]
can you maybe add something to the crash that say something like "a double entry detected" ?

**Comment by AbsolemJackdaw** [comment]
you mean this ? 
> Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:painting_variant / paintings:dp_afternoon_volcano] at different raw IDs (-1, 136)! If you're trying to override an item, use .set(), not .register()!

**Comment by AbsolemJackdaw** [comment]
minecraft throws the error for you, I dont have to :P

**Comment by TheSnowyChickens** [comment]
Okay. :D

So, first problem solved.

**Comment by AbsolemJackdaw** [comment]
removing the double whale entry allowed me to start up the game. 

if you got other issues please let me know ! 

if everything is solved, feel free to close the issue

~~also, use darkhax's mod :D~~ the mod is a small one and does not add to the load you are trying to save your cpu from :)

**Comment by TheSnowyChickens** [comment]
Quick to the server thing: as I had the running version and I pasted the download link to the server properties, MC, after downloading, issued me the resourcepack on server side. Could this be the same issue with the double id's ? (or spelling issues)

This:
![grafik](https://user-images.githubusercontent.com/29357962/188502344-f1963d63-8113-45eb-8e0e-af58e1646360.png)

**Comment by AbsolemJackdaw** [comment]
I'm not sure what you are explaining, but if the server has the correct, working resourcepack, and makes you download it, then it should work. 

I am not aware of duplicates made by having the pack and you downloading the same pack from the server, but if the client ends up with two packs that add the same paintings, then you may have the same crash related to duplicate entries.

The crash you showed me however, was for painting entries missing

**Comment by AbsolemJackdaw** [comment]
my knowledge doesnt reach that far, but if the download failed, the server may have detected you already had the pack. 

give the server the working pack, and the client a working pack, and let me know ! I'm going to end up learning something today too :D

**Comment by TheSnowyChickens** [comment]
Okay, after my League round I'm patching everything and let you know. 

Thanks already. 

I close the issue, I think we can still write after closing it.

**Comment by TheSnowyChickens** [comment]
now I broke everything.
![grafik](https://user-images.githubusercontent.com/29357962/188506044-c05d9407-4c5e-4ca9-8338-4580815c0d36.png)

I removed the double "whale_dream", but I still can't start the game. :(

The few custom "ai_" pictures are very large (1024x1024 and more (but it's fine with the 16 row)), how large can a picture be ?

**Comment by AbsolemJackdaw** [comment]
the limit of the picture size is determined by your hardware

try a bigger wall ?

**Comment by TheSnowyChickens** [comment]
the wall is not the problem, your tiny 16x16 pictures are not loaded².
(the resourcepack broke it)

GPU and CPU are not problem.

**Comment by TheSnowyChickens** [comment]
I am very sure it's again a tiny tiny tiny issue from my side, but after hours of trying I lost the overview.

I deleted the resourcepack string out of the options.txt, but I can't start the game.

**Comment by AbsolemJackdaw** [comment]
you aren't putting anything in the painting.json file in the painting folder right? only custom stuff in a resourcepack ?

**Comment by AbsolemJackdaw** [comment]
https://discord.gg/8MEdFZh

lets talk this over on my channel

**Comment by AbsolemJackdaw** [comment]
Fix found : 
the pack needs to be added to the resourcepack folder before the game starts, or the game needs to be restarted after dragging an d dropping the pack in the resourcepack gui.

**Comment by TheSnowyChickens** [comment]
Good job my hero.
