### ISSUE TITLE
Custom Size Config

### ISSUE THREAD

**Issue by hiyhiyhiy** [ArtixAllMighty/Paintings--#85]
Every time I use the custom config size in Painting Pack Maker, and use the resource pack the images don't show. Only when I use the presets the images show.

**Comment by AbsolemJackdaw** [comment]
(moved ticket to appropriate repo)

**Comment by AbsolemJackdaw** [comment]
@hiyhiyhiy an update was made and is availaible at https://github.com/AbsolemJackdaw/PaintingPackMaker
