### ISSUE TITLE
All paintings are showing as missing textures

### ISSUE THREAD

**Issue by Mohotzgui** [ArtixAllMighty/Paintings--#86]
After ensuring the paths are correct and zipping it up the MOD shows all the paintings in the GUI. It shows them all as missing textures. I am using fabric 1.92,2. It displays the ones in your JAR and the ones from my main resource pack with their textures just fine. The painting pack has worked for several versions before. Any thoughts? I'm sure its an easy fix but any help would be appreciated. Thanks.

**Comment by AbsolemJackdaw** [comment]
theres probably nothing wrong.
you can upload the latest.log here if you'd like, the answer is very likely in it. 
if not , please make sure your resourcepack is loaded by the game. 

you can also always use the [painting pack maker ](https://github.com/AbsolemJackdaw/PaintingPackMaker)

**Comment by AxelCornelisPXL** [comment]
given the lack of a follow up, i'm closing the ticket
