### ISSUE TITLE
Game breaking bug in 1.20.1

### ISSUE THREAD

**Issue by KaZAamM** [ArtixAllMighty/Paintings--#90]
Hello. After so many hours of trying to find what is causing an issue with entering into a boat and talking with villagers, I found that Paintings++ somehow disables those features. 

There is a possibility that another mod that I have installed conflicts with it, but considering that I have nearly 300 mods loaded on Fabric, it would take far too much effort to find that.

Anyways, since disabling Paintings++ I can now enter a boat and talk to villagers. If I re-enable the mod, those features are disabled.

**Comment by strikerrocker** [comment]
Fixed in release [1.20.1-11.0.0.1](https://legacy.curseforge.com/minecraft/mc-mods/paintings/files/4656715)
