### ISSUE TITLE
[1.12.2] Paintings with transparency show back texture

### ISSUE THREAD

**Issue by Stars-Collective** [ArtixAllMighty/Paintings--#96]
![Screenshot 2024-03-25 095545](https://github.com/AbsolemJackdaw/Paintings--/assets/66085024/7307bea7-df60-46fe-9b43-32a5fd71f551)
I have been using the latest version of Paintings ++ for Minecraft 1.12.2, for the better part of a year. This issue only started today

**Comment by AbsolemJackdaw** [comment]
Have you started using another mod recently that may have caused this? 
1.12.2 is also out of support for now. 
I'm planning a backport of the modern version somewhere in the near future
